### ISSUE TITLE
Clear purpose for `README.md` - use GitHub Pages?

### ISSUE THREAD

**Issue by widdowquinn** [nickp60/Nolan_et_al_2018#1]
GitHub provides for the use of GitHub Pages, which is a (relatively) easy way to set up a website from a repository. The setup can be as easy as writing a landing page in the repository's `README.md` and selecting to use GitHub Pages in the repo's Settings.

When doing this, non-specialists/people who might be put off by GitHub can navigate the pages you create like any other webpage, which is an advantage for supplementary information.

Also, when doing this, the links to files don't have to take into account GitHub's own structure. For instance a link such as:

`https://github.com/nickp60/Nolan_et_al_2018/blob/master/scripts/aggregate_data.md`

would become

`./scripts/aggregate_data.md`

with no need to refer to the `blob` or `master` branch.

I recommend building files with this ultimate style of presentation in mind, e.g. `knit`ting the `.Rmd` files to produce `.html` which can then be linked from the landing `README.md`, as with (for example) [this supplementary info](https://widdowquinn.github.io/SI_Holmes_etal_2017/)

**Comment by nickp60** [comment]
Alright, Github pages is set up, I have gotten rid of the .md files, changed the links to hit the html pages, and added a link to the repo description to bring users to the website.  The links are now relative to the project directory.
